# Generated by Django 4.2.2 on 2023-06-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_category',
            field=models.CharField(choices=[('Web_Development', 'Web Application'), ('Software_Development', 'Software Packages'), ('Machine Learning Project', 'Data Science Project')], max_length=30),
        ),
    ]
