# Generated by Django 4.2.2 on 2023-06-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_category',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('Software Development', 'Software Development'), ('Machine Learning Project', 'Machine Learning Project')], max_length=30),
        ),
    ]
