# Generated by Django 4.2.2 on 2023-06-29 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_project_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
