# Generated by Django 4.2.2 on 2023-06-26 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_project_manager',
        ),
    ]
