# Generated by Django 4.2.2 on 2023-06-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='short_summary',
            field=models.CharField(max_length=40),
        ),
    ]
