# Generated by Django 4.2.2 on 2023-06-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_task_short_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='short_summary',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Backlog', 'back-log'), ('Not Started', 'not-started'), ('In Progress', 'in-progress'), ('Complete', 'complete')], max_length=25),
        ),
    ]
